services:
  bind9:
    image: ubuntu/bind9
    container_name: bind9
    ports:
      - "5354:5353/udp"
      - "5354:5353/tcp"
    volumes:
      - ./bind9-config/named.conf:/etc/bind/named.conf
      - ./bind9-config/db.equipo4docker.com:/etc/bind/zones/db.equipo4docker.com
    restart: always
    cap_add:
      - NET_ADMIN

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

  apache:
    build:
      context: ./apache
    container_name: apache
    ports:
      - "80:80"
    depends_on:
      - mariadb
    volumes:
      - ./www:/var/www/html
      - ./apache-config:/etc/apache2/sites-available

  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    volumes:
      - ./conf.d/loadbalancer.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
      - "8082:80"
    depends_on:
      - apache

volumes:
  mariadb_data: